general:
  production: false
  baseUrl: "http://localhost:8994"
  listenPort: "8994"
  aesIv: "16byteaesiv11111"
  md5Salt: "someMd5Salt"

tgService:
  enabled: false
  botToken: ""
  adminUID: 0
  workerNum: 3

redis:
  host: "localhost"
  port: "6379"
  password: ""
  db: 0