general:
  production: false
  web_enabled: true
  baseUrl: "http://localhost:8994"
  listenPort: "8994"
  aesIv: "16byteaesiv11111"
  md5Salt: "someMd5Salt"

tgService:
  enabled: false
  botToken: ""
  adminUID: 0
  handleWorkerNum: 1
  msgSenderNum: 5

redis:
  host: "localhost"
  port: "6379"
  password: ""
  db: 0

statistics_report:
  v6_51_la: false
  v6_51_la_js1: ''
  v6_51_la_js2: ''